import type { Department } from '@/types';

export const DEPARTMENT_OPTIONS: Array<{ value: Department; label: string }> = [
  { value: 'KOREAN_LANGUAGE_CULTURE', label: '한국언어문화전공' },
  { value: 'JAPANESE_REGIONAL_STUDIES', label: '일본지역학전공' },
  { value: 'CHINESE_REGIONAL_STUDIES', label: '중국지역학전공' },
  { value: 'ENGLISH_REGIONAL_STUDIES', label: '영미지역학전공' },
  { value: 'FRENCH_REGIONAL_STUDIES', label: '프랑스지역학전공' },
  { value: 'GERMAN_REGIONAL_STUDIES', label: '독일지역학전공' },
  { value: 'RUSSIAN_CENTRAL_ASIA_REGIONAL_STUDIES', label: '러시아중앙아시아지역학전공' },
  { value: 'COMMUNICATION_DESIGN', label: '커뮤니케이션디자인전공' },
  { value: 'FASHION_DESIGN', label: '패션디자인전공' },
  { value: 'TEXTILE_DESIGN', label: '텍스타일디자인전공' },
  { value: 'SPACE_DESIGN', label: '스페이스디자인전공' },
  { value: 'CERAMIC_DESIGN', label: '세라믹디자인전공' },
  { value: 'INDUSTRIAL_DESIGN', label: '산업디자인전공' },
  { value: 'AR_VR_MEDIA_DESIGN', label: 'AR/VR미디어디자인전공' },
  { value: 'FILM_VIDEO', label: '영화영상전공' },
  { value: 'THEATER', label: '연극전공' },
  { value: 'STAGE_ART', label: '무대미술전공' },
  { value: 'PHOTO_VIDEO_MEDIA', label: '사진영상미디어전공' },
  { value: 'DIGITAL_COMICS_VIDEO', label: '디지털만화영상전공' },
  { value: 'ARTS_CULTURE_MANAGEMENT', label: '예술문화경영전공' },
  { value: 'AI_MEDIA_CONTENT', label: 'AI미디어콘텐츠전공' },
  { value: 'GLOBAL_FINANCE_MANAGEMENT', label: '글로벌금융경영전공' },
  { value: 'FOOD_ENGINEERING', label: '식품공학전공' },
  { value: 'GREEN_SMART_CITY', label: '그린스마트시티전공' },
  { value: 'NURSING', label: '간호학전공' },
  { value: 'BIO_FOOD_TECH', label: '바이오식품공학전공' },
  { value: 'SPORTS_CONVERGENCE', label: '스포츠융합전공' },
  { value: 'ELECTRONICS_ENGINEERING', label: '전자공학전공' },
  { value: 'SOFTWARE', label: '소프트웨어학과' },
  { value: 'SMART_INFO_COMMUNICATION_ENGINEERING', label: '스마트정보통신공학전공' },
  { value: 'INDUSTRIAL_MANAGEMENT_ENGINEERING', label: '산업경영공학전공' },
  { value: 'GREEN_CHEMICAL_ENGINEERING', label: '그린화학공학전공' },
  { value: 'CIVIL_SYSTEM_ENGINEERING', label: '건설시스템공학전공' },
  { value: 'INFORMATION_SECURITY_ENGINEERING', label: '정보보안공학전공' },
  { value: 'SYSTEM_SEMICONDUCTOR_ENGINEERING', label: '시스템반도체공학전공' },
  { value: 'HUMAN_INTELLIGENT_ROBOT_ENGINEERING', label: '휴먼지능로봇공학전공' },
  { value: 'INTELLIGENT_ROBOTICS', label: '지능형로봇학과' },
  { value: 'AI_MOBILITY_ENGINEERING', label: 'AI모빌리티공학전공' },
  { value: 'SMART_IT_CONVERGENCE_ENGINEERING', label: '스마트IT융합공학전공' },
  { value: 'SELF_DIRECTED_MAJOR', label: '자기설계융합전공' },
];
